<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TestOrderService.Application\TestOrderService.Application.csproj"/>
        <ProjectReference Include="..\TestOrderService.Domain\TestOrderService.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Confluent.Kafka" Version="13.0.0"/>
        <PackageReference Include="Google.Protobuf" Version="3.33.1"/>
        <PackageReference Include="Grpc.Net.Client" Version="2.76.0-pre1"/>
        <PackageReference Include="Grpc.Tools" Version="2.76.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.11"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="gRPC\Protos\patient.proto" GrpcServices="Client"/>
        <Protobuf Include="gRPC\Protos\privilege.proto" GrpcServices="Client"/>
        <Protobuf Include="gRPC\Protos\user.proto" GrpcServices="Client"/>
        <Protobuf Include="gRPC\Protos\privilege.proto" GrpcServices="Client"/>
    </ItemGroup>
</Project>
