<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TestOrderService.Domain\TestOrderService.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.1.0"/>
        <PackageReference Include="FluentValidation" Version="12.1.0"/>
        <PackageReference Include="Mapster" Version="7.4.0"/>
        <PackageReference Include="MediatR" Version="13.1.0"/>
    </ItemGroup>

</Project>
