// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestOrderService.Infrastructure.Data;

#nullable disable

namespace TestOrderService.Infrastructure.Migrations
{
    [DbContext(typeof(TestOrderServiceDbContext))]
    [Migration("20251126080116_AddTestResultsTable")]
    partial class AddTestResultsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestOrderService.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateById")
                        .HasColumnType("uuid");

                    b.Property<string>("CreateByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TestOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdateByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CommentId");

                    b.HasIndex("TestOrderId");

                    b.HasIndex("CreateById", "UpdateById", "TestOrderId");

                    b.ToTable("Comments", "public");
                });

            modelBuilder.Entity("TestOrderService.Domain.Entities.TestOrder", b =>
                {
                    b.Property<Guid>("TestOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunById")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TestOrderDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid");

                    b.HasKey("TestOrderId");

                    b.HasIndex("PatientId", "ReviewId", "CreateById", "UpdateById");

                    b.ToTable("TestOrders", "public");
                });

            modelBuilder.Entity("TestOrderService.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TestDefinitionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestResultDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("TestResultId");

                    b.HasIndex("TestOrderId");

                    b.ToTable("TestResults", "public");
                });

            modelBuilder.Entity("TestOrderService.Domain.Entities.Comment", b =>
                {
                    b.HasOne("TestOrderService.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany("Comments")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("TestOrderService.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("TestOrderService.Domain.Entities.TestOrder", "TestOrder")
                        .WithMany("TestResults")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("TestOrderService.Domain.Entities.TestOrder", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
