<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>939ca807-aa3d-4acc-ae94-b354db4aa375</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.1.0"/>
        <PackageReference Include="FluentValidation" Version="12.1.0"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0"/>
        <PackageReference Include="Google.Protobuf" Version="3.33.1"/>
        <PackageReference Include="Grpc" Version="2.46.6"/>
        <PackageReference Include="Grpc.AspNetCore.Server" Version="2.71.0"/>
        <PackageReference Include="Grpc.Net.ClientFactory" Version="2.76.0-pre1"/>
        <PackageReference Include="Grpc.Tools" Version="2.76.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11"/>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.10.3"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TestOrderService.Application\TestOrderService.Application.csproj"/>
        <ProjectReference Include="..\TestOrderService.Domain\TestOrderService.Domain.csproj"/>
        <ProjectReference Include="..\TestOrderService.Infrastructure\TestOrderService.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="gRPC\Protos\TestOrderProto\test_order.proto" GrpcServices="Server"/>
    </ItemGroup>
</Project>
